name: Deploy Jekyll with GitHub Pages

on:
  # Sadece ana dalda yapılan itişlerde çalışır
  push:
    branches:
      - "master"

  # Actions sekmesinden manuel olarak çalıştırılabilir
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Ruby
        uses: actions/setup-ruby@v2
        with:
          ruby-version: 2.7

      - name: Install Dependencies
        run: |
          gem install bundler
          bundle install

      - name: Build with Jekyll
        run: |
          bundle exec jekyll build

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: jekyll-site
          path: _site

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v2
        with:
          name: jekyll-site
          path: _site

      - name: Deploy to GitHub Pages
        uses: actions/gh-pages@v3
        with:
          build_dir: ./_site
